### ISSUE TITLE
Add 'close' option, default True, to stdio_mgr

### ISSUE THREAD

**Issue by bskinn** [bskinn/stdio-mgr#3]
There may be use cases where having the various `StringIO` &c. stay alive after exiting the context would be useful.

**Comment by jayvdb** [comment]
This one is important for deploying stdio-mgr into existing codebases with minimal changes.

https://github.com/open-contracting/ocdskit/blob/master/tests/commands/test_validate.py and all of the other test modules in that directory use `assert actual.getvalue() == 'foo'` after the context manager has exited.  My guess is they would prefer to get rid of all the monkey patching by adopting stdio-mgr, but would not like their core assertions to all be indented making the change very large and breaking basic git blame.  As they are tests, the cleanup of resources is not high importance.
