### ISSUE TITLE
Python 2.7 backport

### ISSUE THREAD

**Issue by bskinn** [bskinn/stdio-mgr#34]
Per [here](https://github.com/kvas-it/pytest-console-scripts/issues/24#issuecomment-516061081), potentially useful for some projects still on the Python 2 tail.

**Comment by jayvdb** [comment]
I suggest that we build for py3.x only until we're happy with what will be in v2, and then try py27 support on temp branches and make a decision if it is worth it.

**Comment by bskinn** [comment]
Py2 is firmly EOL. `stdio-mgr` will be Python 3 only.
